name: Deploy kafka to dev and prod
on: push
permissions:
  security-events: write
  actions: read
  packages: write
  id-token: write
  contents: read

jobs:
  jar-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/jar-app.yaml@main
    secrets: inherit
    with:
      app: dinesykmeldte-kafka
